### ISSUE TITLE
Show and Tell: Twitter API

### ISSUE THREAD

**Issue by jonathanschlue** [fccleipzig/website-project#21]
We need an introduction into the Twitter API for backoffice convenience.

**Comment by zweief** [comment]
We could build a twitter bot for tweeting news about our meetup and let it run on Heroku? I did this and it was a funny little exercise.

**Comment by jonathanschlue** [comment]
After talking about #24 tomorrow, we could even integrate the Twitter and other Social Media APIs in our node.js backend.
