### ISSUE TITLE
Website Mockup [FIGMA]

### ISSUE THREAD

**Issue by danmcatee** [fccleipzig/website-project#3]
### Description

We need a basic idea about how our website should look.
I created a project on Figma whoever wants to do the mockups gets an invite from me.
Since there is no pull request needed for this issue, you are welcome to work on it with multiple people. 

https://www.figma.com/files/project/362258/fcc-website

* [ ] Homepage Mockup
* [ ] Come up with ideas for subpages
* [ ] Subpage Mockups

**Comment by jonathanschlue** [comment]
Can you please provide a link to the Figma project?

**Comment by jonathanschlue** [comment]
Use `CC - ATTRIBUTION-NONCOMMERCIAL-SHAREALIKE` at Imprint page.

**Comment by danmcatee** [comment]
Add imprint page

**Comment by jonathanschlue** [comment]
Add Daniel as Collaborator

**Comment by jonathanschlue** [comment]
Basic structure, discussed at 30.10.17 @Dezentrale

# Pages

 - HOME (Link über Logo)
   - kurz und bündig: What's Next
 - About
   - sollte kurz sein
   - 1 Foto
 - BLOG
   - Fotos
   - Veranstaltungstexte
 - Team
 - Projects
 - Imprint
 - Locations

**Comment by valeriakori** [comment]
Output und Anregungen von 06.11.:

- einzelne reiter für projects und slides
- Imprint in footer; Inhalt: CC
- genauer Text für Mission Info
- what's next auf homepage (aus MeetUpAPI)
- checken ob Bilder royalty free sind
- Reiter Header: HOME über Logo; About, Blog; Projects; (Slides?)
- nächstes MeetUp ganz oben
- danach Kontakt
