### ISSUE TITLE
Write CSS Styleguide

### ISSUE THREAD

**Issue by danmcatee** [fccleipzig/website-project#4]
### Description

We need a CSS Styleguide for a seamless and consistent workflow. 
You should make up your mind about a color palette to use throughout the website.
Naming conventions, formatting rules and measurements to use would be useful too.

https://github.com/airbnb/css

* [x] Define Color Palette
* [x] Naming Conventions
* [x] Define measurements to use
* [x] Define formatting rules

**Comment by Eik-S** [comment]
So did we decide to use sass with scss syntax from the beginning or should we use "vanilla" css for the first draft 
(I would recommend using scss from the beginning, but stick to basic features like color variables and nesting)

**Comment by danmcatee** [comment]
Good point, I agree with you. Let's use SCSS
