### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by danmcatee** [fccleipzig/website-project#5]
### Description

We need to decide which license we gonna choose for our project.
Someone should dive into licenses and bring up which one and why he/she chose a particular one.
Here's an article for inspiration: [How open source licenses work](https://medium.freecodecamp.org/how-open-source-licenses-work-and-how-to-add-them-to-your-projects-34310c3cf94)

* [ ] Research licenses
* [ ] Present results at sprint
* [ ] Democratically choose a license

**Comment by Eik-S** [comment]
Need help? got some free time and could join.

**Comment by danmcatee** [comment]
Sure

**Comment by Eik-S** [comment]
Should we split up to content & project licenses? could research project licenses or also content if you already researched one of them. @zweief

**Comment by zweief** [comment]
If you want to research the content license this would be great.

**Comment by Eik-S** [comment]
:+1:

**Comment by Eik-S** [comment]
I wrote a small presentation for content licenses (creative commons), you can find it in the feature branch [here](https://rawgit.com/fccleipzig/slides/licensing/_LICENSING/index.html#/l) for now.

**Comment by jonathanschlue** [comment]
Temporary content license set to `CC - ATTRIBUTION-NONCOMMERCIAL-SHAREALIKE`.
